# Generated by Django 6.1.1 on 2026-09-19 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_transactionproof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='shared_savings_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
